os: linux
dist: bionic
language: python
python:
  - "3.7"
services:
  - docker
install:
  - sudo apt-get update
  - python setup.py egg_info
  - pip install -r photonai_neuro.egg-info/requires.txt
  - pip install --upgrade git+https://github.com/wwu-mmll/photonai.git@develop
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - PYTHONPATH=./ pytest ./test --cov=./photonai_neuro
after_success:
  - coveralls